
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/dev/cmake/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.19044 - AMD64
...
